=== netgroup-polito/vnf-modeling/Conti/nf-dev-master-e6d0e0e33115819338cf2f4cab229d682a635242/xsd/LogicalExpressions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.example.org/LogicalExpressions" 
		xmlns:tns="http://www.example.org/LogicalExpressions" 
		elementFormDefault="qualified">
		
	<annotation>
		<documentation>LO stands for Logical Operator,LU stands for Logical Unit,LF stands for Logical Function</documentation>
	</annotation>	
		
	<element name="Result" type="tns:ExpressionResult">
		<key name="PacketNameKey" >
			<selector xpath="tns:Packet"></selector>
			<field xpath="@Name"></field>
		</key>
		
		<key name="NodeNameKey">
			<selector xpath="tns:Node"></selector>
			<field xpath="@Name"></field>
		</key>
		
		<key name="TimeNameKey">
			<selector xpath="tns:Time"></selector>
			<field xpath="@Name"></field>
		</key>
		
		<!-- keyref name="PacketRecvRef" refer="tns:PacketNameKey">
			<selector xpath=".//tns:Recv"></selector>
			<field xpath="@Packet_in"></field>
		</keyref>
		
		<keyref name="PacketSendRef" refer="tns:PacketNameKey">
			<selector xpath=".//tns:Send"></selector>
			<field xpath="@Packet_out"></field>
		</keyref-->
	
	</element>

	<complexType name="LogicalOperator" abstract="true">
		<attribute name="OperatorType"></attribute>
	</complexType>
	
	<complexType name="LogicalUnit" abstract="true">
		<attribute name="Name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="LogicalFunction" abstract="true">
		<attribute name="Name" type="string"></attribute>
	</complexType>

    <complexType name="ExpressionObject">
    	<choice>
		  	<element name="And" type="tns:LO_And"></element>
			<element name="Or" type="tns:LO_Or"></element>
			<element name="Not" type="tns:LO_Not"></element>
			<element name="Equal" type="tns:LO_Equals"></element>
			<element name="GreaterThan" type="tns:LO_Greater_Than"></element>
			<element name="GreaterThanOrEqual" type="tns:LO_Greater_Than_or_Equal"></element>
			<element name="LessThan" type="tns:LO_Less_Than"></element>
			<element name="LessThanOrEqual" type="tns:LO_Less_Than_or_Equal"></element>
			<element name="Implies" type="tns:LO_Implies"></element>
			<element name="Exist" type="tns:LO_Exist"></element>
			<element name="Send" type="tns:LF_Send"></element>
			<element name="Recv" type="tns:LF_Recv"></element>
			<element name="MatchEntry" type="tns:LF_MatchEntry"></element>
			<element name="FieldOf" type="tns:LF_FieldOf"></element>
			<element name="IsInternal" type="tns:LF_IsInternal"></element>
			<element name="Param" type="string"></element>
    	</choice>
    </complexType>
	
	<complexType name="ExpressionResult">	
		<sequence>
			<element name="TableSize" type="int"></element>
			<element name="DataDriven" type="boolean"></element>
			<element name="TableFields" type="string" minOccurs="0" maxOccurs="unbounded"></element>
			<choice maxOccurs="unbounded">
				<element name="Node" type="tns:LU_Node"></element>
				<element name="Packet" type="tns:LU_Packet"></element>
				<element name="Time" type="tns:LU_Time"></element>
			</choice>
			<element name="LogicalExpressionResult" maxOccurs="unbounded" type="tns:ExpressionObject"></element>
		</sequence>
	</complexType>

    <complexType name="LO_And">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="Expression" type="tns:ExpressionObject" minOccurs="2" maxOccurs="unbounded"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType> 
    
     <complexType name="LO_Or">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="Expression" type="tns:ExpressionObject" minOccurs="2" maxOccurs="unbounded"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType> 
    
     <complexType name="LO_Not">
     	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="Expression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType> 
    
     <complexType name="LO_Equals">
    	 <complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="LeftExpression" type="tns:ExpressionObject"></element>
    				<element name="RightExpression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType> 
    
     <complexType name="LO_Greater_Than">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="LeftExpression" type="tns:ExpressionObject"></element>
    				<element name="RightExpression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType> 
    
    <complexType name="LO_Greater_Than_or_Equal">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="LeftExpression" type="tns:ExpressionObject"></element>
    				<element name="RightExpression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
   	<complexType name="LO_Less_Than">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="LeftExpression" type="tns:ExpressionObject"></element>
    				<element name="RightExpression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="LO_Less_Than_or_Equal">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="LeftExpression" type="tns:ExpressionObject"></element>
    				<element name="RightExpression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="LO_Implies">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="AntecedentExpression" type="tns:ExpressionObject"></element>
    				<element name="ConsequentExpression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>	
    </complexType>
    
    <complexType name="LO_Exist">
    	<complexContent>
    		<extension base="tns:LogicalOperator">
    			<sequence>
    				<element name="Unit" type="string" maxOccurs="unbounded"></element>
    				<element name="Expression" type="tns:ExpressionObject"></element>
    			</sequence>
    		</extension>
    	</complexContent>   	
    </complexType>
      
    <complexType name="LU_Node"> 
    	<complexContent>
    		<extension base="tns:LogicalUnit">
    			<attribute name="Value" type="string"></attribute>    		
    		</extension>
    	</complexContent>	
    </complexType>  
    
    <complexType name="LU_Packet">	
    	<complexContent>
    		<extension base="tns:LogicalUnit">
    			<attribute name="ETH_SRC" type="string"></attribute>
    			<attribute name="ETH_DST" type="string"></attribute>
    			<attribute name="IP_SRC" type="string"></attribute>
				<attribute name="IP_DST" type="string"></attribute>
				<attribute name="PORT_SRC" type="string"></attribute>
				<attribute name="PORT_DST" type="string"></attribute>  
				<attribute name="TRANSPORT_PROTOCOL" type="string"></attribute>
				<attribute name="APPLICATION_PROTOCOL" type="string"></attribute>
				<attribute name="L7DATA"></attribute>
    		</extension>
    	</complexContent>			 		
    </complexType> 
    
    <complexType name="LU_Time">
    	<complexContent>
    		<extension base="tns:LogicalUnit">
    			<attribute name="Value" type="string"></attribute>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="LF_Send"> 
    	<complexContent>
    		<extension base="tns:LogicalFunction">
    			<sequence>
					<element name="Source" type="string"></element>
					<element name="Destination" type="string"></element>
					<element name="Packet_out" type="string"></element>
					<element name="Time_out" type="string"></element>
				</sequence>
    		</extension>
    	</complexContent>
    
	
    </complexType>  
    
    <complexType name="LF_Recv">   	
    	<complexContent>
    		<extension base="tns:LogicalFunction">
	    		<sequence>
					<element name="Source" type="string"></element>
					<element name="Destination" type="string"></element>
					<element name="Packet_in" type="string"></element>
					<element name="Time_in" type="string"></element>
				</sequence>
    		</extension>
    	</complexContent>
    
		 	
    </complexType>
    
    <complexType name="LF_MatchEntry">
    	<complexContent>
    		<extension base="tns:LogicalFunction">
	    		<sequence>
	    			<element name="Value" type="tns:LF_FieldOf" maxOccurs="unbounded" ></element>
				</sequence>   
    		</extension>
    	</complexContent>
				 
    </complexType>
  
   	<complexType name="LF_FieldOf">
   		<complexContent>
   			<extension base="tns:LogicalFunction">
	   			<sequence>
					<element name="Unit" type="string"></element>
					<element name="Field" type="string"></element>		
				</sequence>
   			</extension>
   		</complexContent>
		  		
   	</complexType>
   	
   	<complexType name="LF_IsInternal">
   		<complexContent>
   			<extension base="tns:LogicalFunction">
   				<sequence>
   					<element name="FieldOf" type="tns:LF_FieldOf"></element>
   				</sequence>
   			</extension>
   		</complexContent>
   		
   	</complexType>
 	   
</schema>

=== netgroup-polito/vnf-modeling/Conti/nf-dev-master-e6d0e0e33115819338cf2f4cab229d682a635242/xsd/Rule_EndHost.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Result xmlns="http://www.example.org/LogicalExpressions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/LogicalExpressions LogicalExpressions.xsd">
    <TableSize>0</TableSize>
    <DataDriven>false</DataDriven>
    <IndirectNF>false</IndirectNF>
    <Node Name="n_0"/>
    <Node Name="n_1"/>
    <Node Name="n_EndHost"/>
    <Packet Name="p_0"/>
    <Packet Name="p_1"/>
    <Time Name="t_0"/>
    <Time Name="t_1"/>
    <LogicalExpressionResult>
        <Implies>
            <AntecedentExpression>
                <Send>
                    <Source>n_EndHost</Source>
                    <Destination>n_0</Destination>
                    <Packet_out>p_0</Packet_out>
                    <Time_out>t_0</Time_out>
                </Send>
            </AntecedentExpression>
            <ConsequentExpression>
                <Exist>
                    <Unit>n_1</Unit>
                    <Unit>p_1</Unit>
                    <Unit>t_1</Unit>
                    <Expression>
                        <And>
                            <Expression>
<Recv>
    <Source>n_1</Source>
    <Destination>n_EndHost</Destination>
    <Packet_in>p_1</Packet_in>
    <Time_in>t_1</Time_in>
</Recv>
                            </Expression>
                            <Expression>
<LessThan>
    <LeftExpression>
        <Param>t_1</Param>
    </LeftExpression>
    <RightExpression>
        <Param>t_0</Param>
    </RightExpression>
</LessThan>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>APPLICATION_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>DNS_RESPONSE</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>IP_SRC</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>IP_DST</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>PORT_SRC</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>PORT_DST</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>IP_DST</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>L7DATA</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>PORT_DST</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>HTTP_PORT_80</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>APPLICATION_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>HTTP_REQUEST</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>L7DATA</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>REQUESTED_URL</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>TRANSPORT_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>TRANSPORT_PROTOCOL</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                        </And>
                    </Expression>
                </Exist>
            </ConsequentExpression>
        </Implies>
    </LogicalExpressionResult>
    <LogicalExpressionResult>
        <And>
            <Expression>
                <Send>
                    <Source>n_EndHost</Source>
                    <Destination>n_0</Destination>
                    <Packet_out>p_0</Packet_out>
                    <Time_out>t_0</Time_out>
                </Send>
            </Expression>
            <Expression>
                <Equal>
                    <LeftExpression>
                        <FieldOf>
                            <Unit>p_0</Unit>
                            <Field>IP_SRC</Field>
                        </FieldOf>
                    </LeftExpression>
                    <RightExpression>
                        <Param>ip_EndHost</Param>
                    </RightExpression>
                </Equal>
            </Expression>
            <Expression>
                <Equal>
                    <LeftExpression>
                        <FieldOf>
                            <Unit>p_0</Unit>
                            <Field>PORT_SRC</Field>
                        </FieldOf>
                    </LeftExpression>
                    <RightExpression>
                        <Param>value_0</Param>
                    </RightExpression>
                </Equal>
            </Expression>
            <Expression>
                <Equal>
                    <LeftExpression>
                        <FieldOf>
                            <Unit>p_0</Unit>
                            <Field>IP_DST</Field>
                        </FieldOf>
                    </LeftExpression>
                    <RightExpression>
                        <Param>ip_Local_Dns</Param>
                    </RightExpression>
                </Equal>
            </Expression>
            <Expression>
                <Equal>
                    <LeftExpression>
                        <FieldOf>
                            <Unit>p_0</Unit>
                            <Field>PORT_DST</Field>
                        </FieldOf>
                    </LeftExpression>
                    <RightExpression>
                        <Param>DNS_PORT_53</Param>
                    </RightExpression>
                </Equal>
            </Expression>
            <Expression>
                <Equal>
                    <LeftExpression>
                        <FieldOf>
                            <Unit>p_0</Unit>
                            <Field>APPLICATION_PROTOCOL</Field>
                        </FieldOf>
                    </LeftExpression>
                    <RightExpression>
                        <Param>DNS_REQUEST</Param>
                    </RightExpression>
                </Equal>
            </Expression>
            <Expression>
                <Equal>
                    <LeftExpression>
                        <FieldOf>
                            <Unit>p_0</Unit>
                            <Field>L7DATA</Field>
                        </FieldOf>
                    </LeftExpression>
                    <RightExpression>
                        <Param>REQUESTED_URL</Param>
                    </RightExpression>
                </Equal>
            </Expression>
        </And>
    </LogicalExpressionResult>
</Result>

=== netgroup-polito/vnf-modeling/Conti/nf-dev-master-e6d0e0e33115819338cf2f4cab229d682a635242/xsd/Rule_WebServer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Result xmlns="http://www.example.org/LogicalExpressions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/LogicalExpressions LogicalExpressions.xsd">
    <TableSize>1</TableSize>
    <DataDriven>false</DataDriven>
    <TableFields>ApplicationProtocol</TableFields>
    <Node Name="n_0"/>
    <Node Name="n_1"/>
    <Node Name="n_WebServer"/>
    <Packet Name="p_0"/>
    <Packet Name="p_1"/>
    <Time Name="t_0"/>
    <Time Name="t_1"/>
    <LogicalExpressionResult>
        <Implies>
            <AntecedentExpression>
                <Send>
                    <Source>n_WebServer</Source>
                    <Destination>n_0</Destination>
                    <Packet_out>p_0</Packet_out>
                    <Time_out>t_0</Time_out>
                </Send>
            </AntecedentExpression>
            <ConsequentExpression>
                <Exist>
                    <Unit>n_1</Unit>
                    <Unit>p_1</Unit>
                    <Unit>t_1</Unit>
                    <Expression>
                        <And>
                            <Expression>
<Recv>
    <Source>n_1</Source>
    <Destination>n_WebServer</Destination>
    <Packet_in>p_1</Packet_in>
    <Time_in>t_1</Time_in>
</Recv>
                            </Expression>
                            <Expression>
<LessThan>
    <LeftExpression>
        <Param>t_1</Param>
    </LeftExpression>
    <RightExpression>
        <Param>t_0</Param>
    </RightExpression>
</LessThan>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>APPLICATION_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>HTTP_REQUEST</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<MatchEntry>
    <Value>
        <Unit>p_1</Unit>
        <Field>L7DATA</Field>
    </Value>
</MatchEntry>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>IP_SRC</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>IP_DST</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>PORT_SRC</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>PORT_DST</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>IP_DST</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>IP_SRC</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>PORT_DST</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>PORT_SRC</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>APPLICATION_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>HTTP_RESPONSE</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>L7DATA</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>value_0</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>TRANSPORT_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>TRANSPORT_PROTOCOL</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                        </And>
                    </Expression>
                </Exist>
            </ConsequentExpression>
        </Implies>
    </LogicalExpressionResult>
</Result>

=== netgroup-polito/vnf-modeling/Conti/nf-dev-master-e6d0e0e33115819338cf2f4cab229d682a635242/xsd/Rule_MailServer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Result xmlns="http://www.example.org/LogicalExpressions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/LogicalExpressions LogicalExpressions.xsd">
    <TableSize>0</TableSize>
    <DataDriven>false</DataDriven>
    <Node Name="n_0"/>
    <Node Name="n_1"/>
    <Node Name="n_MailServer"/>
    <Packet Name="p_0"/>
    <Packet Name="p_1"/>
    <Time Name="t_0"/>
    <Time Name="t_1"/>
    <LogicalExpressionResult>
        <Implies>
            <AntecedentExpression>
                <Send>
                    <Source>n_MailServer</Source>
                    <Destination>n_0</Destination>
                    <Packet_out>p_0</Packet_out>
                    <Time_out>t_0</Time_out>
                </Send>
            </AntecedentExpression>
            <ConsequentExpression>
                <Exist>
                    <Unit>n_1</Unit>
                    <Unit>p_1</Unit>
                    <Unit>t_1</Unit>
                    <Expression>
                        <And>
                            <Expression>
<Recv>
    <Source>n_1</Source>
    <Destination>n_MailServer</Destination>
    <Packet_in>p_1</Packet_in>
    <Time_in>t_1</Time_in>
</Recv>
                            </Expression>
                            <Expression>
<LessThan>
    <LeftExpression>
        <Param>t_1</Param>
    </LeftExpression>
    <RightExpression>
        <Param>t_0</Param>
    </RightExpression>
</LessThan>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>APPLICATION_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>POP3_REQUEST</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>IP_SRC</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>IP_DST</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>PORT_SRC</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>PORT_DST</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>IP_DST</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>IP_SRC</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>PORT_DST</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>PORT_SRC</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>APPLICATION_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>POP3_RESPONSE</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>L7DATA</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <Param>RESPONSE</Param>
    </RightExpression>
</Equal>
                            </Expression>
                            <Expression>
<Equal>
    <LeftExpression>
        <FieldOf>
            <Unit>p_0</Unit>
            <Field>TRANSPORT_PROTOCOL</Field>
        </FieldOf>
    </LeftExpression>
    <RightExpression>
        <FieldOf>
            <Unit>p_1</Unit>
            <Field>TRANSPORT_PROTOCOL</Field>
        </FieldOf>
    </RightExpression>
</Equal>
                            </Expression>
                        </And>
                    </Expression>
                </Exist>
            </ConsequentExpression>
        </Implies>
    </LogicalExpressionResult>
</Result>
